version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.13.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes: 
      - "$PROMETHEUS_DATA:/prometheus rw"
      - "$PROMETHEUS_CONFIG:/etc/prometheus/prometheus.yml"
    extra_hosts: 
      - supper-app-host:$HOST_IP
  grafana:
    image: grafana/grafana:6.4.3
    container_name: grafana
    ports:
      - 3000:3000
    volumes: 
      - "$GRAFANA_DATA:/var/lib/grafana rw"
    extra_hosts: 
      - prometheus-host:$HOST_IP
