swagger: "2.0"
info:
  version: 1.0.0
  title: capture-api
  description: Web Capture API
basePath: /capture/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  
  CaptureBody:
    type: object
    title: Web Capture Request body
    required:
      - url
      - requestId
    properties:
      url:
        type: string
        example: "https://google.com"
      requestId:
        type: string
        example: "2c5ea4c0-4067-11e9-8bad-9b1deb4d3b7d"

paths:

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  /metrics:
    get:
      tags:
        - Metrics
      responses:
        200:
          description: Prometheus metrics

  /health:
    get:
      tags:
        - Health
      responses:
        200:
          description: Service health indicator

  /:
    post:
      tags:
        - Capture
      parameters:
        - name: url
          in: body
          description: URL to be captured
          required: true
          schema: 
            $ref: "#/definitions/CaptureBody"
        - name: requestId
          in: body
          description: Request identifier
          required: true
          schema: 
            $ref: "#/definitions/CaptureBody"
      responses:
        200:
          description: Success capture of URL
        422:
          description: URL cannot be captured
